# Generated by Django 5.0.7 on 2024-09-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
